#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Editor
export EDITOR='vim'
export VISUAL='vim'

# Git command aliases (oh-my-zsh)
alias ga='git add'
alias gc!='git commit -v --amend'
alias gca!='git commit -v -a --amend'
alias gd='git diff'
alias gdca='git diff --cached'
alias glog='git log --oneline --decorate --graph'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbs='git rebase --skip'
alias gst='git status'

# rbenv
if [[ -d "$HOME/.rbenv/" ]]; then
  export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi
